# Generated by Django 4.2.13 on 2024-07-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name cinema')),
                ('preview_image', models.ImageField(upload_to='media/cinema/%Y/%m/%d/', verbose_name='image')),
                ('date', models.DateField(verbose_name='date')),
                ('date_update', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name genres')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name actor')),
                ('surname', models.CharField(max_length=100, verbose_name='surname')),
                ('age', models.IntegerField()),
                ('cinema', models.ManyToManyField(to='app.cinema')),
            ],
        ),
    ]
