# Generated by Django 4.2.13 on 2024-07-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cinema_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='cinema',
        ),
        migrations.AddField(
            model_name='cinema',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.genres'),
            preserve_default=False,
        ),
    ]
